fields:
  low_top_padding:
    label: 15px di padding top?
    type: toggle
    width: 1/2
  padding:
    label: Padding tutto intorno?
    type: toggle
    when:
      top_padding: false
      bottom_padding: false
    width: 1/2
  top_padding:
    label: Padding sopra?
    type: toggle
    width: 1/3
    when:
      padding: false
  bottom_padding:
    label: Padding sotto?
    type: toggle
    width: 1/3
    when:
      padding: false
  no_inner_padding:
    label: Nessun padding interno
    type: toggle
    width: 1/3
  bg_random:
    label: Sfondo cangiante random?
    type: toggle
    width: 1/2
  bg_image_switch:
    label: Sfondo con immagine?
    type: toggle
    width: 1/2
  bg_image:
    label: Immagine di sfondo
    type: files
    max: 1
    when:
      bg_image_switch: true
  bg_color:
    label: Sfondo colorato?
    type: toggle
    when:
      bg_random: false
  bg_color_code:
    label: Codice colore [esadec.]
    type: text
    when:
      bg_color: true
      bg_random: false
  flex_grow:
    label: Le colonne hanno flex grow?
    type: toggle
  flex_switch:
    label: Questa riga usa "FLEX"?
    type: toggle
  justify_content:
    label: Allineamento orizzontale 
    type: select
    width: 1/3
    columns: 2
    options:
      flex-start: SX
      flex-end: DX
      center: Centro
      space-between: Distribuiti
      space-around: Distribuiti con aria ai lati
    when:
      flex_switch: true
  align_items:
    label: Allineamento verticale
    type: select
    width: 1/3
    columns: 2
    options:
      flex-start: Sopra
      flex-end: Sotto
      center: Al centro
    when:
      flex_switch: true
  sync:
    label: Funzione scroll sincronizzato
    type: toggle
    default: false
    width: 1/2
  sticky:
    label: Funzione scroll sticky
    type: toggle
    default: false
    width: 1/2
  sticky_offset:
    label: Valore dell'offset dello sticky
    type: number
    default: 100
    when:
      sticky: true
    width: 1/2

