title: Default Page
icon: dashboard

options: options/changeTemplate

tabs:
  #
  contenuto: fields/layout
  #
  proprieta: fields/proprieta
  #
  sottopagine: tabs/pagine
  #
  configurazione: fields/configurazione
